yaresa/api/urls.py
from django.conf.urls import url

from api.views import signin, reset_pin, get_summary, get_profile, get_medigraph, get_socialhistory, get_allergy_list, \
        get_medical_history_list, get_medication_list, get_surgery_list, get_bmi, get_bp_list

__author__ = 'andrews'

app_name = "core"
urlpatterns = [
        url(r'^accounts/signin', signin, name="signin"),
        url(r'^accounts/reset-password', reset_pin, name="reset-password"),
        url(r'^get-summary', get_summary, name="summary"),
        url(r'^get-profile', get_profile, name="profile"),
        url(r'^get-social-history', get_socialhistory, name="social-history"),
        url(r'^get-medi-graph', get_medigraph, name="medigraph"),
        url(r'^get-allergy-list', get_allergy_list, name="allergy-list"),
        url(r'^get-medical-history-list', get_medical_history_list, name="medical-history-list"),
        url(r'^get-medication-list', get_medication_list, name="medication-list"),
        url(r'^get-surgery-list',get_surgery_list, name="surgery-list"),
        url(r'^get-bmi', get_bmi, name="bmi"),
        url(r'^get-bp-list', get_bp_list, name="bp-list"),


]

yaresa/core/urls.py
from core.views.core_view import dashboard, add_new_user, add_medical_info, user_list, user_detail, user_condition, \
    user_allergy, user_medication, user_account_reset, blood_group_count, sickling_count, user_bloodpressure, \
    user_bmi, g6pd_count, user_surgery, user_fastbloodsugar, user_fullbloodcount, user_lipidprofile, user_renaltest, \
    user_livertest, male_prostatetest, user_urinetest, add_doctor, add_nurse, add_general_supervisor, add_organization, \
    add_partners, doctorpatients_list, patient_transfer, partners_list, doctors_list, nurses_list, partner_details, \
    partner_view_patient, organizations_list, supervisors_list, add_drugs, add_conditions, add_speciality

from core.views.home_views import index, signin, sign_out
from django.conf.urls import url

from core.views.logging.logging_views import my_activities

__author__ = 'andrews'



app_name="core"
urlpatterns = [
    url(r'^$', index, name="home"),

    url(r'^accounts/signin', signin, name="signin"),
    url(r'^accounts/signout', sign_out, name="signout"),
    url(r'^dashboard', dashboard, name="dashboard"),
    url(r'^user-list', user_list, name="user-list"),
    url(r'^doctors-list', doctors_list , name="doctors-list"),
    url(r'^nurses-list', nurses_list, name="nurses-list"),
    url(r'^partner-list', partners_list, name="partners-list"),
    url(r'^supervisors-list', supervisors_list, name="supervisors-list"),
    url(r'^doctor-patients-list', doctorpatients_list, name="doctor-patients-list"),
    url(r'^add-user', add_new_user, name="new-user"),
    url(r'^user-account-reset/(?P<pk>\d+)', user_account_reset, name="user-account-medication"),
    url(r'^add-medi-info/(?P<pk>\d+)', add_medical_info, name="add-medi-info"),
    url(r'^user-detail/(?P<pk>\d+)', user_detail, name="user-detail"),
    url(r'^partner-detail/(?P<pk>\d+)', partner_details, name="partner-detail"),
    url(r'^user-condition/(?P<pk>\d+)', user_condition, name="user-condition"),
    url(r'^user-allergy/(?P<pk>\d+)', user_allergy, name="user-allergy"),
    url(r'^user-medication/(?P<pk>\d+)', user_medication, name="user-medication"),
    url(r'^user-bmi/(?P<pk>\d+)', user_bmi, name="user-bmi"),
    url(r'^user-bloodpressure/(?P<pk>\d+)', user_bloodpressure, name="user-bloodpressure"),
    url(r'^user-surgery/(?P<pk>\d+)', user_surgery, name="user-surgery"),
    url(r'^user-fasting-blood-sugar/(?P<pk>\d+)', user_fastbloodsugar, name="user-fastbloodsugar"),
    url(r'^user-full-blood-count/(?P<pk>\d+)', user_fullbloodcount, name="user-fullbloodcount"),
    url(r'^user-lipid-profile/(?P<pk>\d+)', user_lipidprofile, name="user-lipidprofile"),
    url(r'^user-renal-function/(?P<pk>\d+)', user_renaltest, name="user-renalfunction"),
    url(r'^user-liver-function/(?P<pk>\d+)', user_livertest, name="user-liverfunction"),
    url(r'^user-urine-test/(?P<pk>\d+)', user_urinetest, name="user-urinetest"),
    url(r'^user-prostate-test/(?P<pk>\d+)', male_prostatetest, name="male-prostatetest"),



    url(r'^blood-group-count', blood_group_count, name="blood-group-count"),
    url(r'^sickling-status-count', sickling_count, name="sickling-count"),
    url(r'^g6pd-count', g6pd_count, name="g6pd-count"),

    url(r'^add-doctor', add_doctor, name="new-doctor"),
    url(r'^add-nurse', add_nurse, name="new-nurse"),
    url(r'^add-general-supervisor', add_general_supervisor, name="new-generalsupervisor"),
    url(r'^add-organization', add_organization, name="new-organization"),
    url(r'^add-partner', add_partners, name="new-partner"),

    url(r'^patient-transfer/(?P<pk>\d+)', patient_transfer, name="patient-transfer"),
    url(r'^partner-patient', partner_view_patient, name="partner-view-patient"),
    url(r'^organizations-list', organizations_list , name="organizations-list"),

    url(r'^add-drugs', add_drugs, name="new-drug"),
    url(r'^add-conditions', add_conditions, name="new-condition"),
    url(r'^add-speciality', add_speciality, name="new-speciality"),

    url(r'^logging/my-activity', my_activities, name="my_activities"),

]

yaresa/yaresa/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from yaresa import settings

urlpatterns = [
    url(r'^',include('core.urls')),
    url(r'^admin/', admin.site.urls),
    url('api/yaresa/', include('api.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yaresa/core/models/allergy.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models

class Allergy(BaseModel):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,null=True)
    type = models.CharField(max_length=255,null=True)

yaresa/core/models/auth_user_demographic.py
from core.core_util import get_object_or_none
from core.models.base_model import BaseModel
from django.contrib.auth.models import User, Group
from django.db import models
from datetime import date
# Create your models here.
from yaresa import settings

sex = (("Male", "MALE"), ("Female", "FEMALE"))
marital = (("Married", "MARRIED"), ("Single", "SINGLE"), ("Divorced", "DIVORCED"), ("Widowed", "WIDOWED"))
religion = (("Christianity","Christianity"),("Islam","Islam"),("Traditional","Traditional"),("Other","Other"),("None","None"))
region_of_residence = (("Ahafo Region","Ahafo Region"),("Ashanti Region","Ashanti Region"),("Bono East Region","Bono East Region"),
                       ("Bono Region","Bono Region"),("Central Region","Central Region"),("Eastern Region","Eastern Region"),
                       ("Greater Accra Region","Greater Accra Region"),("Northern Region","Northern Region"),("North East Region","North East Region"),
                       ("Oti Region","Oti Region"),("Savannah Region","Savannah Region"),("Upper East Region","Upper East Region"),
                       ("Upper West Region","Upper West Region"),("Volta Region","Volta Region"),("Western Region","Western Region"),
                       ("Western North Region","Western North Region"))

class AuthUserDemographic(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    picture = models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')
    title = models.CharField(max_length= 30,null=True)
    first_name = models.CharField(max_length=255,null=True)
    other_name = models.CharField(max_length=255,null=True)
    unique_id = models.CharField(max_length=255,null=True)
    surname = models.CharField(max_length=255,null=True,verbose_name="Surname")
    sex = models.CharField(max_length=255,choices=sex,verbose_name="Gender",default="Male")
    date_of_birth = models.DateField(verbose_name="Date of Birth")
    nationality = models.CharField(max_length=255,null=True)
    religion = models.CharField(max_length=255,choices=religion,null=True)
    marital_status = models.CharField(max_length=255,choices=marital,default="Single")
    address = models.CharField(max_length=255,blank=True,null=True)
    occupation = models.CharField(max_length=255,null=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=255,null=True)
    emergency_contact_name = models.CharField(max_length=255,null=True)
    emergency_contact_mobile = models.CharField(max_length=255,null=True)
    emergency_contact_address = models.CharField(max_length=255, null=True)
    emergency_contact_email = models.EmailField(null=True)
    first_login = models.BooleanField(default=True)
    speciality = models.CharField(max_length=255,null=True)
    hospital_name = models.CharField(max_length=255,null=True)
    mdc_certificate = models.CharField(max_length=255,null=True)
    role = models.CharField(max_length=225,null=True)
    denomination = models.CharField(max_length=225,null=True)
    region_of_residence = models.CharField(max_length=255,choices=region_of_residence,null=True)
    city_and_town = models.CharField(max_length=225,null=True)

    def __str__(self):
        return '{} {} {}'.format(self.first_name, self.other_name, self.surname)

    def is_patient(self, ):
        users_in_group = Group.objects.get(name="Patient").user_set.all()
        return True if self.user in users_in_group else False

    def is_doctor(self, ):
        users_in_group = Group.objects.get(name="Doctor").user_set.all()
        return True if self.user in users_in_group else False

    def is_nurse(self, ):
        users_in_group = Group.objects.get(name="Nurse").user_set.all()
        return True if self.user in users_in_group else False

    def is_generalsupervisor(self, ):
        users_in_group = Group.objects.get(name="General Supervisor").user_set.all()
        return True if self.user in users_in_group else False


    def get_age(self):
        born = self.date_of_birth
        today = date.today()
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

    @property
    def get_absolute_image_url(self):
        return "{0}{1}".format(settings.MEDIA_URL, self.picture.url)

    @classmethod
    def get_auth_user_by_id(cls,id):
        user = get_object_or_none(User,id=id)
        return get_object_or_none(cls,user=user)

yaresa/core/models/base_model.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

yaresa/core/models/biostatistics.py
from core.models.auth_user_demographic import AuthUserDemographic
from django.contrib.auth.models import User
from django.db import models

__author__ = 'andrews'

class Height(models.Model):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    height = models.CharField(max_length=255,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Weight(models.Model):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    weight = models.CharField(max_length=255,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Blood_Pressure(models.Model):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    systolic = models.CharField(max_length=255,null=True)
    diastolic = models.CharField(max_length=255,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

yaresa/core/models/conditions.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models


__author__ = 'sam'

class Conditions(models.Model):
    name = models.CharField(max_length=255, null=True)



    def __str__(self):
        return '{}'.format(self.name,)

yaresa/core/models/contactus.py
from django.db import models

__author__ = 'sam'

class Contactus(models.Model):
    yourname = models.CharField(max_length=255,null=True)
    youremail = models.CharField(max_length=255,null=True)
    yournumber = models.CharField(max_length=255,null=True)
    subject = models.CharField(max_length=255,null=True)
    message = models.CharField(max_length=1500,null=True)

yaresa/core/models/drugs.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models


__author__ = 'sam'

class Drugs(models.Model):
    name = models.CharField(max_length=255, null=True)



    def __str__(self):
        return '{}'.format(self.name,)

yaresa/core/models/fasting_blood_sugar.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models


__author__ = 'sam'


class Fasting_blood_sugar(BaseModel):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    test_result = models.CharField(max_length=255, null=True)
    saved_result = models.CharField(max_length=255, null=True)
    docs_comments = models.CharField(max_length=3000, null=True)
    test_date = models.DateField()
    next_fbs_test = models.DateField(null=True)

yaresa/core/models/full_blood_count.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models
from yaresa import settings


__author__ = 'sam'


class Full_blood_count(BaseModel):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    fbc_image_scan = models.ImageField(upload_to='pic_folder/', default='pic_folder/None/no-img.jpg')
    red_blood_cell = models.CharField(max_length=255, null=True)
    hemoglobin = models.CharField(max_length=255, null=True)
    hematocrit = models.CharField(max_length=255, null=True)
    white_blood_cell = models.CharField(max_length=255, null=True)
    platelet = models.CharField(max_length=255, null=True)
    neutrophil = models.CharField(max_length=255, null=True)
    lymphocyte = models.CharField(max_length=255, null=True)
    full_blood_count_date = models.DateField()
    next_full_blood_count_date = models.DateField(null=True)
    docs_comments = models.CharField(max_length=3000, null=True)

    @property
    def get_absolute_image_url(self):
        return "{0}{1}".format(settings.MEDIA_URL, self.fbc_image_scan.url)

yaresa/core/models/lipid_profile.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models
from yaresa import settings


__author__ = 'sam'


class Lipid_profile(BaseModel):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    total_cholesterol = models.CharField(max_length=255, null=True)
    hdl_cholesterol = models.CharField(max_length=255, null=True)
    ldl_cholesterol = models.CharField(max_length=255, null=True)
    triglycerides = models.CharField(max_length=255, null=True)
    lipid_profile_date = models.DateField()
    next_lipid_test = models.DateField()
    lipid_scan = models.ImageField(upload_to='pic_folder/', default='pic_folder/None/no-img.jpg')
    docs_comments = models.CharField(max_length=3000, null=True)

    @property
    def get_absolute_image_url(self):
        return "{0}{1}".format(settings.MEDIA_URL, self.lipid_scan.url)

yaresa/core/models/organizations.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models


__author__ = 'sam'


class Organization(models.Model):
    type = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)
    reps_contact = models.CharField(max_length=255, null=True)
    reps_email = models.CharField(max_length=255, null=True)


    def __str__(self):
        return '{} {}'.format(self.type, self.name)

yaresa/core/models/patient_partner_transfer.py
from core.models import Partners, AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models

class PatientPartnerTransfer(BaseModel):
    patient = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE, null=True, related_name="patient")
    partner = models.ForeignKey(Partners, on_delete=models.CASCADE, null=True, related_name="partner")
    created_by = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE, null=True, related_name="created_by")
    remark = models.CharField(max_length = 200,null=True)
    status = models.CharField(max_length = 30,null=True,default="Active")

yaresa/core/models/renal_function_test.py
from core.models import AuthUserDemographic
from core.models.base_model import BaseModel
from django.contrib.auth.models import User
from django.db import models
from yaresa import settings


__author__ = 'sam'

class Renal_function_test(BaseModel):
    user = models.ForeignKey(AuthUserDemographic, on_delete=models.CASCADE)
    creatinine = models.CharField(max_length=255, null=True)
    urea = models.CharField(max_length=255, null=True)
    gfr = models.CharField(max_length=255, null=True)
    renal_test_date = models.DateField()
    next_renal_test = models.DateField()
    renal_scan = models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')
    docs_comments = models.CharField(max_length=3000, null=True)

    @property
    def get_absolute_image_url(self):
        return "{0}{1}".format(settings.MEDIA_URL, self.renal_scan.url)

yaresa/core/templates/user-renal-function.html
{% extends 'dashboardbase.html' %}

        {% block title %}New BP{% endblock %}

        {% block content %}
            {% load static %}


    <div class="container-fluid">



	<div class="container">
	  <div class="row">
		<div class="col-md-12">
         <div class="card">
            <div class="container" style="margin-top: 20px">
                   <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
			<div class="row">
                <div class="col-md-6 offset-md-4">
   <div class="chip modalbtn lighten-4"><b>#</b>
    {{ user.unique_id }}
   </div>
  <div class="chip">
     <a href="{% url 'core:user-detail' pk=user.id %}" class="gray-text">
	 <img src="{{ user.picture.url }}" alt="Contact Person"> {{ user.first_name }} {{ user.surname }}
	 </a>
 </div>
                </div>
			</div>
			
            <label class="h4 title text-uppercase flex-center mt-5 mb-2">Renal Function Test</label>
			<br><br>

				<div class="form-row">
				     <div class="col-md-4 offset-md-2 py-2">
                           <div class="md-form form-group">
                                <label for="id_creatinine" class="control-label">Creatinine (umol/L)</label>

						        {{ userrenaltest.creatinine }}

                           </div>
                                </div>



						 <div class="col-sm-4 py-2">
							<p for="">Creatinine Range : <span>
                                <input type="text" class="form-control" id="creatinine" name="creatinine" placeholder="000 umol/L" disabled>
							</span>
							</p>
						</div>

				</div>

				<div class="form-row">
				     <div class="col-md-4 offset-md-2 py-2">
                           <div class="md-form form-group">
                                <label for="id_urea" class="control-label">Urea (mmol/L)</label>

						       {{ userrenaltest.urea }}

                           </div>
                                </div>



						 <div class="col-sm-4 py-2">
							<p >Urea Range : <span>
							    <input type="text" class="form-control" id="urea" name="urea" placeholder="0.00 mmol/L" disabled>
							</span>
							</p>
						</div>

				</div>

				<div class="form-row">
				     <div class="col-md-3 offset-md-2 py-2">
                           <div class="md-form form-group">
                                <label for="id_gfr" class="control-label">Glomerular Filtration Rate (GFR) </label>

						        {{ userrenaltest.gfr }}

                           </div>
                                </div>



						 <div class="col-sm-5 py-2">
							<p>GFR Range: <span>
                                <input type="text" class="form-control" id="gfr" name="gfr" placeholder="000 mL/min/1.73m2" disabled>
							</span>
							</p>
						</div>

				</div>

				
				<div class="form-row">
						<div class="col-md-4 offset-md-2 py-2">
                           <div class="md-form form-group">
                                <label for="id_renal_test_date" class="control-label">Current Test Date</label>

						        {{ userrenaltest.renal_test_date }}

                           </div>
                         </div>


						 <div class="col-sm-4 py-2">
							<div class="md-form form-group">
                                <label for="id_next_renal_test" class="control-label">Next Test Date</label>

						        {{ userrenaltest.next_renal_test }}

                           </div>
						</div>

				</div>
				
				<div class="form-row pic-row mt-4">
          <div class="card pic-card col-md-4 col-sm-6 col-xs-8 offset-sm-4">

			  <p class="h4 text-center grey-text text-uppercase pt-2">upload renal scan</p><br>
			   <div class="row d-flex justify-content-center">
			  <div class="file-field">
        <div class="mb-4" align="center">
       <img id="imgId" src="{% static 'images/scan-avatar.jpg' %} " style="height:150px;width:150px;border-radius:10px;">
        </div>
        <div class="d-flex justify-content-center">
            <div class="btn btn-mdb-color btn-rounded float-left">
                <span>Add Test Scan</span>
                <input name="renal_scan" id="id_renal_scan" type="file" onchange="document.getElementById('imgId').src = window.URL.createObjectURL(this.files[0])">
            </div>
        </div>
		</div>
         </div>

           </div>
    </div><br><br>
	
	
			<div class="form-row">
						<div class="col-md-8 offset-md-2 py-2">
                           <div class="md-form shadow-textarea form-group">
							<i class="fa fa-pencil prefix pr-3"></i>
                                <label for="id_docs_comments" class="control-label pl-3">Doctor's Comments</label>

						        {{ userrenaltest.docs_comments }}

                           </div>
                        </div>


						 
			</div>

	
				<div class="col-md-3 offset-md-5 mb-3">

                        <button class="btn btn-rounded modalbtn" type="submit">Add Renal Test</button>
                </div>





                       </form>
            </div>
                </div></div></div>

		<div class="row mt-5" style="margin-bottom:100px;">
			<div class="col-md-12">
      <div class="card" style="margin-top: 20px">

             <div class="container" style="margin-top: 20px">

            <div class="row">
                <div class="col-md-12">


				 <div class="table-wrapper">
				 <!-- Trying to get the date for the next test to show on the top of the table.-->
				 <p class="h5 flex-center orange-text">Kidney Function Test</p>
					<!-- {% for renal in renalfunction %}
					<p class="flex-center orange-text h6">{{ renal.next_renal_test }}</p>
							{% endfor %} -->
            <!--Table-->
            <table id="factorytable" class="table table-hover table-responsive-sm table-sm btn-table m-0">

                <!--Table head-->
                <thead>

                            <tr>
								<th class="th-sm">Creatinine</th>
								<th class="th-sm">Urea</th>
								<th class="th-sm">GFR</th>
								<th class="th-sm">Doctor's Comments</th>
                                <th class="th-sm">Test Date</th>
								<th class="th-sm"></th>
                            </tr>

                </thead>
                <!--Table head-->

                <!--Table body-->
                <tbody>
                     {% for renal in renalfunction %}

                        <tr>
								<td>{{ renal.creatinine }} umol/L</td>
                                <td>{{ renal.urea }} mg/dL</td>
                                <td>{{ renal.gfr }} mL/min/1.73m<sup>2</sup></td>
								<td>{{ renal.docs_comments }} </td>
								<td>{{ renal.renal_test_date }}</td>
                                  <td>
                                <div class="btn-group">
                                    <a href=""><i class="fa fa-eye ml-2  text-info" data-toggle="tooltip" title="View Details"></i></a>
                                </div>
								<div class="btn-group">
                                    <a href=""><i class="fa fa-pencil ml-2 text-success" data-toggle="tooltip" title="Edit"></i></a>
                                </div>
								<div class="btn-group">
                                    <a href=""><i class="fa fa-trash ml-2  text-danger" data-toggle="tooltip" title="Delete"></i></a>
                                </div>
								</td>

                        </tr>
                     {% endfor %}
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
        </div>





                </div>
            </div>

             </div>
        </div></div></div>
    </div>
    </div>
{% endblock %}

yaresa/core/templates/view_partner_patient.html
{% extends 'dashboardbase.html' %}

        {% block title %}New user{% endblock %}

        {% block content %}
            {% load static %}


    <div class="container-fluid">


<div class="card card-cascade narrower">

    <!--Card image-->
    <div class="view gradient-card-header heavy-rain-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">

        <div>
             <a href="{% url 'core:new-user' %}"><button type="button"  data-toggle="tooltip" data-placement="top" title="Add new user" class="btn btn-outline-white btn-rounded btn-sm px-2">
                 <i class="fa fa-plus mt-0"></i></button></a>
        </div>

        <h4 class="white-text mx-3">Users</h4>

        <div>
           <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fa fa-info-circle mt-0"></i></button>
        </div>

    </div>
    <!--/Card image-->

    <div class="px-4">

        <div class="table-wrapper">
            <!--Table-->
            <table id="factorytable" class="table table-hover mb-0">

                <!--Table head-->
                <thead>

                            <tr>

                                <th class="th-lg">ID </th>
                                <th class="th-lg"> Name</th>
                                 <th class="th-lg">Email</th>
                                <th class="th-lg">Mobile</th>

                                <th class="th-lg"></th>
                            </tr>

                </thead>
                <!--Table head-->

                <!--Table body-->
                <tbody>
                     {% for user in user_list %}

                        <tr>

                                <td>{{ user.patient.unique_id }}</td>
                                <td>{{ user.patient }}</td>
                                <td>{{ user.patient.email }}</td>
                                <td>{{ user.patient.mobile }}</td>
                                <td>
                                    <div class="btn-group">
                                    <a href="{% url 'core:user-detail' pk=user.patient.id %}"><button type="button" class="btn btn-rounded modalbtn">View</button></a>


                                    <button type="button" class="btn modalbtn dropdown-toggle px-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="sr-only">Toggle Dropdown</span>
                                </button>
<div class="dropdown-menu force-scroll">
	
	<a class="dropdown-item" href="{% url 'core:user-allergy' pk=user.patient.id %}">Allergy</a>
	<a class="dropdown-item" href="{% url 'core:user-bloodpressure' pk=user.patient.id %}">Blood Pressure</a>
	<a class="dropdown-item" href="{% url 'core:user-bmi' pk=user.patient.id %}">BMI</a>
    <a class="dropdown-item" href="{% url 'core:user-condition' pk=user.patient.id %}">Conditions</a>
	<a class="dropdown-item" href="{% url 'core:user-fastbloodsugar' pk=user.patient.id %}">Fasting Blood Sugar</a>
	<a class="dropdown-item" href="{% url 'core:user-fullbloodcount' pk=user.patient.id %}">Full Blood Count</a>
	<a class="dropdown-item" href="{% url 'core:user-lipidprofile' pk=user.patient.id %}">Lipid Profile</a>
	<a class="dropdown-item" href="{% url 'core:user-liverfunction' pk=user.patient.id %}">Liver Function</a>
    <a class="dropdown-item" href="{% url 'core:user-medication' pk=user.patient.id %}">Medication</a>
	<a class="dropdown-item" href="{% url 'core:male-prostatetest' pk=user.patient.id %}">Prostate Specific</a>
	<a class="dropdown-item" href="{% url 'core:user-renalfunction' pk=user.patient.id %}">Renal Function</a>
	<a class="dropdown-item" href="{% url 'core:user-surgery' pk=user.patient.id %}">Surgery</a>
	<a class="dropdown-item" href="{% url 'core:user-urinetest' pk=user.patient.id %}">Urine Test</a>
     
     
	 
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'core:user-account-medication' pk=user.id %}">Reset Account</a>
    <a class="dropdown-item" href="#">Deactivate Account</a>
  </div>
                                </div>
                                </td>

                        </tr>
                     {% endfor %}
                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
        </div>

        <hr class="my-0">


    </div>
</div>





    </div>
    {% endblock %}